### 模拟客户端（如果要删除所有客户端，target_count设置为0即可）
POST {{host}}/client?target_count=100

### 开启订阅风暴
POST {{host}}/sub

### 开启发布风暴
POST {{host}}/pub
Content-Type: application/json

{
  "pubDurationSecond": 10,
  "pubFrequencyMs": 1000,
  "qos": 0
}
