### 增加客户端
POST {{host}}/client?target_count=400

### 减少客户端
DELETE {{host}}/client?target_count=800

### 开启订阅风暴
POST {{host}}/sub

### 开启发布风暴
POST {{host}}/pub
Content-Type: application/json

{
  "msgCount": 3,
  "pushFrequencyMs": 1000,
  "qos": 0
}
